# Generated by Django 4.1.7 on 2023-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "show_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("show_type", models.CharField(max_length=24)),
                ("show_title", models.CharField(max_length=64)),
                ("director", models.CharField(max_length=64)),
                ("cast", models.CharField(max_length=512)),
                ("country", models.CharField(max_length=36)),
                ("date_added", models.DateField()),
                ("release_year", models.IntegerField()),
                ("rating", models.CharField(max_length=10)),
                ("duration", models.CharField(max_length=24)),
            ],
        ),
    ]
