# Generated by Django 4.1.7 on 2023-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="date_added",
            field=models.CharField(max_length=24),
        ),
    ]
